# 示例配置：按需修改，然后保存为程序目录下的`Config.toml`，作为输入参数

# 待编码的文本输入路径
in_path = "TestText.txt"

# 编码及其开销的连接策略：
# SpaceOrPunct - 空格或标点
# NoGap - 无间隔
# Jd6 - 键道6顶功
strat = "SpaceOrPunct"

# 最优编码及其分析报告输出路径（存在则覆写）
out_path = "TestTextCodeReport.txt"

# 键对-开销（当量）路径
costs_path = "Cfg/Costs.tsv"

# 词库（RIME格式）路径
dict_path = "Cfg/Dict.yaml"

# 键盘布局配置
[layout]

# 数字、上、中、下、底排键
rows = [
    "`1234567890-=",
    "qwertyuiop[]\\",
    "asdfghjkl;'",
    "zxcvbnm,./",
    " "
]

# 左拇、食、中、无名、小指键
lefts = [
    " ",
    "4rfv5tgb",
    "3edc",
    "2wsx",
    "`1qaz"
]

# 右拇、食、中、无名、小指键
rights = [
    " ",
    "6yhn7ujm",
    "8ik,",
    "9ol.",
    "0p;/-['=]\\"
]
