# 示例键盘布局配置：按需修改，用于分析编码

# 数字、上、中、下、底排键
rows = [
  "`1234567890-=",
  "qwertyuiop[]\\",
  "asdfghjkl;'",
  "zxcvbnm,./",
  " "
]

# 左拇、食、中、无名、小指键
lefts = [
  " ",
  "4rfv5tgb",
  "3edc",
  "2wsx",
  "`1qaz"
]

# 右拇、食、中、无名、小指键
rights = [
  " ",
  "6yhn7ujm",
  "8ik,",
  "9ol.",
  "0p;/-['=]\\"
]
